apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-monitoring

resources:
- https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/standard/kustomization.yaml

patches:
- path: svc.yaml

