---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments

commonLabels:
  app: payments

resources:
- sa.yaml
- deployment.yaml
- service.yaml
- job.yaml

configMapGenerator:
- name: payments-db-migrations
  files:
    - conf/db/migrations/V0__Initial.sql
