apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/base/templates/crds.yaml
- manifests/base/templates/defaultrevision-validatingwebhookconfiguration.yaml
- manifests/base/templates/reader-serviceaccount.yaml
- manifests/base/templates/zzz_profile.yaml
- manifests/cni/templates/clusterrole.yaml
- manifests/cni/templates/clusterrolebinding.yaml
- manifests/cni/templates/configmap-cni.yaml
- manifests/cni/templates/daemonset.yaml
- manifests/cni/templates/serviceaccount.yaml
- manifests/cni/templates/zzz_profile.yaml
- manifests/istiod/templates/autoscale.yaml
- manifests/istiod/templates/clusterrole.yaml
- manifests/istiod/templates/clusterrolebinding.yaml
- manifests/istiod/templates/configmap-jwks.yaml
- manifests/istiod/templates/configmap-values.yaml
- manifests/istiod/templates/configmap.yaml
- manifests/istiod/templates/deployment.yaml
- manifests/istiod/templates/istiod-injector-configmap.yaml
- manifests/istiod/templates/mutatingwebhook.yaml
- manifests/istiod/templates/poddisruptionbudget.yaml
- manifests/istiod/templates/reader-clusterrole.yaml
- manifests/istiod/templates/reader-clusterrolebinding.yaml
- manifests/istiod/templates/remote-istiod-service.yaml
- manifests/istiod/templates/revision-tags-mwc.yaml
- manifests/istiod/templates/revision-tags-svc.yaml
- manifests/istiod/templates/role.yaml
- manifests/istiod/templates/rolebinding.yaml
- manifests/istiod/templates/service.yaml
- manifests/istiod/templates/serviceaccount.yaml
- manifests/istiod/templates/validatingadmissionpolicy.yaml
- manifests/istiod/templates/validatingwebhookconfiguration.yaml
- manifests/istiod/templates/zzz_profile.yaml
- manifests/ztunnel/templates/daemonset.yaml
- manifests/ztunnel/templates/serviceaccount.yaml
- manifests/ztunnel/templates/zzz_profile.yaml
