apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-kyverno

resources:
- charts/crds/templates/kyverno.io/kyverno.io_cleanuppolicies.yaml
- charts/crds/templates/kyverno.io/kyverno.io_clustercleanuppolicies.yaml
- charts/crds/templates/kyverno.io/kyverno.io_clusterpolicies.yaml
- charts/crds/templates/kyverno.io/kyverno.io_globalcontextentries.yaml
- charts/crds/templates/kyverno.io/kyverno.io_policies.yaml
- charts/crds/templates/kyverno.io/kyverno.io_policyexceptions.yaml
- charts/crds/templates/kyverno.io/kyverno.io_updaterequests.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_deletingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_generatingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_imagevalidatingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_mutatingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_namespaceddeletingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_namespacedimagevalidatingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_namespacedvalidatingpolicies.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_policyexceptions.yaml
- charts/crds/templates/policies.kyverno.io/policies.kyverno.io_validatingpolicies.yaml
- charts/crds/templates/reports.kyverno.io/reports.kyverno.io_clusterephemeralreports.yaml
- charts/crds/templates/reports.kyverno.io/reports.kyverno.io_ephemeralreports.yaml
- charts/crds/templates/wgpolicyk8s.io/wgpolicyk8s.io_clusterpolicyreports.yaml
- charts/crds/templates/wgpolicyk8s.io/wgpolicyk8s.io_policyreports.yaml
- templates/admission-controller/clusterrole.yaml
- templates/admission-controller/clusterrolebinding.yaml
- templates/admission-controller/deployment.yaml
- templates/admission-controller/poddisruptionbudget.yaml
- templates/admission-controller/role.yaml
- templates/admission-controller/rolebinding.yaml
- templates/admission-controller/service.yaml
- templates/admission-controller/serviceaccount.yaml
- templates/background-controller/clusterrole.yaml
- templates/background-controller/clusterrolebinding.yaml
- templates/background-controller/deployment.yaml
- templates/background-controller/poddisruptionbudget.yaml
- templates/background-controller/role.yaml
- templates/background-controller/rolebinding.yaml
- templates/background-controller/service.yaml
- templates/background-controller/serviceaccount.yaml
- templates/cleanup-controller/clusterrole.yaml
- templates/cleanup-controller/clusterrolebinding.yaml
- templates/cleanup-controller/deployment.yaml
- templates/cleanup-controller/poddisruptionbudget.yaml
- templates/cleanup-controller/role.yaml
- templates/cleanup-controller/rolebinding.yaml
- templates/cleanup-controller/service.yaml
- templates/cleanup-controller/serviceaccount.yaml
- templates/config/configmap.yaml
- templates/config/metricsconfigmap.yaml
- templates/hooks/post-upgrade-migrate-resources.yaml
- templates/hooks/pre-delete-remove-mutatingwebhookconfiguration.yaml
- templates/hooks/pre-delete-remove-validatingwebhookconfiguration.yaml
- templates/hooks/pre-delete-scale-to-zero.yaml
- templates/rbac/policies.yaml
- templates/rbac/policyreports.yaml
- templates/rbac/reports.yaml
- templates/rbac/updaterequests.yaml
- templates/reports-controller/clusterrole.yaml
- templates/reports-controller/clusterrolebinding.yaml
- templates/reports-controller/deployment.yaml
- templates/reports-controller/poddisruptionbudget.yaml
- templates/reports-controller/role.yaml
- templates/reports-controller/rolebinding.yaml
- templates/reports-controller/service.yaml
- templates/reports-controller/serviceaccount.yaml
- templates/tests/admission-controller-metrics.yaml
- templates/tests/cleanup-controller-liveness.yaml
- templates/tests/cleanup-controller-metrics.yaml
- templates/tests/cleanup-controller-readiness.yaml
- templates/tests/reports-controller-metrics.yaml
- cluster-policies.yaml
