# https://cert-manager.io/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-certs

resources:
- ../base
- issuers.yaml
