---
# Source: ztunnel/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ztunnel
  namespace: platform-istio-system
  labels:
    app.kubernetes.io/name: ztunnel
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "ztunnel"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.28.3"
    helm.sh/chart: ztunnel-1.28.3
    
  annotations:
    {}
