apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payments-route
spec:
  parentRefs:
    - name: https-gcp-external
      namespace: platform-gateways
      kind: Gateway
      sectionName: https-wildcard-airpay-com
  hostnames:
    - "payments.airpay.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: payments
        port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payments-http-to-https-redirect
spec:
  parentRefs:
    - name: https-gcp-external
      namespace: platform-gateways
      kind: Gateway
      sectionName: http
  hostnames:
    - "payments.airpay.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: payments-security-policy
spec:
  default:
    securityPolicy: ca-waf-rate-limit
  targetRef:
    group: ""
    kind: Service
    name: payments
