apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- templates/cainjector-deployment.yaml
- templates/cainjector-rbac.yaml
- templates/cainjector-service.yaml
- templates/cainjector-serviceaccount.yaml
- templates/controller-config.yaml
- templates/crd-acme.cert-manager.io_challenges.yaml
- templates/crd-acme.cert-manager.io_orders.yaml
- templates/crd-cert-manager.io_certificaterequests.yaml
- templates/crd-cert-manager.io_certificates.yaml
- templates/crd-cert-manager.io_clusterissuers.yaml
- templates/crd-cert-manager.io_issuers.yaml
- templates/deployment.yaml
- templates/rbac.yaml
- templates/service.yaml
- templates/serviceaccount.yaml
- templates/startupapicheck-job.yaml
- templates/startupapicheck-rbac.yaml
- templates/startupapicheck-serviceaccount.yaml
- templates/webhook-deployment.yaml
- templates/webhook-mutating-webhook.yaml
- templates/webhook-rbac.yaml
- templates/webhook-service.yaml
- templates/webhook-serviceaccount.yaml
- templates/webhook-validating-webhook.yaml
