---
# Source: istiod/templates/clusterrolebinding.yaml
# Created if cluster resources are not omitted
# Created if this is not a remote istiod, OR if it is and is also a config cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istiod-clusterrole-platform-istio-system
  labels:
    app: istiod
    release: istiod
    app.kubernetes.io/name: "istiod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "istiod"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.28.3"
    helm.sh/chart: istiod-1.28.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-clusterrole-platform-istio-system
subjects:
  - kind: ServiceAccount
    name: istiod
    namespace: istio-system
---
# Source: istiod/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istiod-gateway-controller-platform-istio-system
  labels:
    app: istiod
    release: istiod
    app.kubernetes.io/name: "istiod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "istiod"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.28.3"
    helm.sh/chart: istiod-1.28.3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-gateway-controller-platform-istio-system
subjects:
- kind: ServiceAccount
  name: istiod
  namespace: istio-system
