---
# Source: istiod/templates/configmap-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: platform-istio-system
  annotations:
    kubernetes.io/description: This ConfigMap contains the Helm values used during chart rendering. This ConfigMap is rendered for debugging purposes and external tooling; modifying these values has no effect.
  labels:
    istio.io/rev: "default"
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istiod
    app.kubernetes.io/name: "istiod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "istiod"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.28.3"
    helm.sh/chart: istiod-1.28.3
data:
  original-values: |-
    {}
  merged-values: |-
    {
      "affinity": {},
      "autoscaleBehavior": {},
      "autoscaleEnabled": true,
      "autoscaleMax": 5,
      "autoscaleMin": 1,
      "base": {
        "enableIstioConfigCRDs": true
      },
      "cni": {
        "enabled": false,
        "provider": "default"
      },
      "configMap": true,
      "cpu": {
        "targetAverageUtilization": 80
      },
      "deploymentAnnotations": {},
      "deploymentLabels": {},
      "env": {},
      "envVarFrom": [],
      "experimental": {
        "stableValidationPolicy": false
      },
      "extraContainerArgs": [],
      "gatewayClasses": {},
      "gateways": {
        "seccompProfile": {},
        "securityContext": {}
      },
      "global": {
        "caAddress": "",
        "caName": "",
        "certSigners": [],
        "configCluster": false,
        "configValidation": true,
        "defaultPodDisruptionBudget": {
          "enabled": true
        },
        "defaultResources": {
          "requests": {
            "cpu": "10m"
          }
        },
        "externalIstiod": false,
        "hub": "docker.io/istio",
        "imagePullPolicy": "",
        "imagePullSecrets": [],
        "istioNamespace": "istio-system",
        "istiod": {
          "enableAnalysis": false
        },
        "logAsJson": false,
        "logging": {
          "level": "default:info"
        },
        "meshID": "",
        "meshNetworks": {},
        "mountMtlsCerts": false,
        "multiCluster": {
          "clusterName": ""
        },
        "nativeNftables": false,
        "network": "",
        "networkPolicy": {
          "enabled": false
        },
        "omitSidecarInjectorConfigMap": false,
        "operatorManageWebhooks": false,
        "pilotCertProvider": "istiod",
        "priorityClassName": "",
        "proxy": {
          "autoInject": "enabled",
          "clusterDomain": "cluster.local",
          "componentLogLevel": "misc:error",
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "image": "proxyv2",
          "includeIPRanges": "*",
          "includeInboundPorts": "*",
          "includeOutboundPorts": "",
          "logLevel": "warning",
          "outlierLogPath": "",
          "privileged": false,
          "readinessFailureThreshold": 4,
          "readinessInitialDelaySeconds": 0,
          "readinessPeriodSeconds": 15,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "seccompProfile": {},
          "startupProbe": {
            "enabled": true,
            "failureThreshold": 600
          },
          "statusPort": 15020,
          "tracer": "none"
        },
        "proxy_init": {
          "forceApplyIptables": false,
          "image": "proxyv2"
        },
        "remotePilotAddress": "",
        "resourceScope": "all",
        "sds": {
          "token": {
            "aud": "istio-ca"
          }
        },
        "sts": {
          "servicePort": 0
        },
        "tag": "1.28.3",
        "variant": "",
        "waypoint": {
          "affinity": {},
          "nodeSelector": {},
          "resources": {
            "limits": {
              "cpu": "2",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "tolerations": [],
          "topologySpreadConstraints": []
        }
      },
      "hub": "",
      "image": "pilot",
      "initContainers": [],
      "ipFamilies": [],
      "ipFamilyPolicy": "",
      "istiodRemote": {
        "enabled": false,
        "enabledLocalInjectorIstiod": false,
        "injectionCABundle": "",
        "injectionPath": "/inject",
        "injectionURL": ""
      },
      "jwksResolverExtraRootCA": "",
      "keepaliveMaxServerConnectionAge": "30m",
      "memory": {},
      "meshConfig": {
        "enablePrometheusMerge": true
      },
      "nodeSelector": {},
      "ownerName": "",
      "pdb": {
        "minAvailable": 1,
        "unhealthyPodEvictionPolicy": ""
      },
      "podAnnotations": {},
      "podLabels": {},
      "replicaCount": 1,
      "resources": {
        "requests": {
          "cpu": "500m",
          "memory": "2048Mi"
        }
      },
      "revision": "",
      "revisionTags": [],
      "rollingMaxSurge": "100%",
      "rollingMaxUnavailable": "25%",
      "seccompProfile": {},
      "serviceAccountAnnotations": {},
      "serviceAnnotations": {},
      "sidecarInjectorWebhook": {
        "alwaysInjectSelector": [],
        "defaultTemplates": [],
        "enableNamespacesByDefault": false,
        "injectedAnnotations": {},
        "neverInjectSelector": [],
        "reinvocationPolicy": "Never",
        "rewriteAppHTTPProbe": true,
        "templates": {}
      },
      "sidecarInjectorWebhookAnnotations": {},
      "tag": "",
      "taint": {
        "enabled": false,
        "namespace": ""
      },
      "telemetry": {
        "enabled": true,
        "v2": {
          "enabled": true,
          "prometheus": {
            "enabled": true
          },
          "stackdriver": {
            "enabled": false
          }
        }
      },
      "tolerations": [],
      "topologySpreadConstraints": [],
      "traceSampling": 1,
      "trustedZtunnelName": "",
      "trustedZtunnelNamespace": "",
      "variant": "",
      "volumeMounts": [],
      "volumes": []
    }
