apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-monitoring

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap-dashboard-provider.yaml
- configmap.yaml
- configmaps-datasources.yaml
- deployment.yaml
- secret.yaml
- service.yaml
- rbac.yaml

