---
# Source: kube-prometheus-stack/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: platform-monitoring
  labels:
    helm.sh/chart: grafana-10.4.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "12.3.0"
    app.kubernetes.io/component: admin-secret
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "ZDJKcGdlZVRvQ3BMWTVuSjZCQ045TkxuZzVGY0dFOEJja3c1a2Jucg=="
  ldap-toml: ""
