
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: atlantis-route
spec:
  parentRefs:
    - name: https-default
      namespace: platform-gateways
      kind: Gateway
      sectionName: https-atlantis-airpay-codes
  hostnames:
    - "atlantis.airpay.codes"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: atlantis
          port: 80
