apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-atlantis

resources:
- sa.yaml
- secrets.yaml
- https://raw.githubusercontent.com/runatlantis/atlantis/refs/heads/main/kustomize/kustomization.yaml

patches:
- path: sts.yaml
- path: svc.yaml

configMapGenerator:
- name: atlantis-repo-config
  files:
  - repo-config.yaml
