apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-monitoring

resources:
- sa.yaml
- receivers.yaml
- store-gateway.yaml
- querier.yaml
- ruler.yaml
- alertmanager.yaml

secretGenerator:
- name: thanos-objstore-config
  files:
    - conf/thanos.yaml

configMapGenerator:
- name: thanos-ruler-rules
  files:
    - conf/slo_rules.yaml
- name: alertmanager-config
  files:
    - conf/alertmanager.yaml

